// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmsdgbfrybwldtipiyxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc2RnYmZyeWJ3bGR0aXBpeXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODIyMjEsImV4cCI6MjA2OTY1ODIyMX0.zHmxTHJb_GBBirJoKjLhc502dNee-TS0yZ_vGkCzk7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});